// Generated by tools/build-site.mjs from data/recipes.json - don't edit by hand.
// 14 checked recipes.
const RECIPES = {
  "fish-cakes": {
    "title": "Fish Cakes",
    "from": "Simy",
    "date": "4/09",
    "serves": null,
    "category": "Meat, Chicken & Fish",
    "person": "simy",
    "pages": [
      "images/pages/p170308.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170308.jpg"
    ],
    "photo": "images/dishes/fish-cakes.jpg",
    "thumb": "images/thumbs/dishes/fish-cakes.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "250g mince hake with carrot & onion (chopped)",
      "1 small egg",
      "Salt, pepper, garlic salt",
      "Small tsp sugar (optional)",
      "Breadcrumbs"
    ],
    "method": [
      "Put in bowl & mix.",
      "Roll into balls & roll in breadcrumbs & flatten gently (if you have time, before frying, put fish cakes on a plate, leave in fridge for a bit).",
      "Oil in frying pan, not too much or too little, very hot oil, turn every few minutes till brown.",
      "Take kitchen paper, put fish cakes to drain oil on them, more paper & drain again.",
      "Then put on cakes, cover with more paper, press gently to remove oil."
    ],
    "notes": [
      "Serve with chips/salad, whatever & chrain."
    ]
  },
  "caponata": {
    "title": "Aletta's Wonderful Sicilian Caponata",
    "from": "Aletta Taranto",
    "date": null,
    "serves": null,
    "category": "Soups & Starters",
    "person": "aletta",
    "pages": [
      "images/pages/p170345.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170345.jpg"
    ],
    "photo": "images/dishes/caponata.jpg",
    "thumb": "images/thumbs/dishes/caponata.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "750g egg fruit (brinjals)",
      "250g green olives (pips removed & chopped)",
      "2 medium onions chopped",
      "1 1/2 celery chopped",
      "2 tablespoons capers",
      "Oil",
      "Vinegar"
    ],
    "method": [
      "Chop egg fruit (brinjals) leaving on skin & fry gently in some oil. Remove from pan.",
      "Boil chopped celery until soft, approx 7 minutes.",
      "Drain celery & fry in the oil. Remove & put together with egg fruit (brinjals) in a dish.",
      "Fry onions in the same oil until light brown & add the olives and fry a little. Remove.",
      "Place all the fried vegetables back in the pan and add approx 2 tablespoons capers.",
      "Season with some sugar & vinegar according to taste.",
      "Leave to cool, pour into bottle. Ready to eat or keep in the fridge."
    ],
    "notes": [
      "This is a wonderful Sicilian cold dish which you can keep in a bottle in the fridge. You can serve with antipasto, or eat with some wonderful bread, cheese & wine or on its own!!"
    ]
  },
  "nonna-s-butter-bean-potato-salad": {
    "title": "Nonna's Butter Bean & Potato Salad",
    "from": "Nonna",
    "date": null,
    "serves": null,
    "category": "Soups & Starters",
    "person": "nonna",
    "pages": [
      "images/pages/p170443.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170443.jpg"
    ],
    "photo": "images/dishes/nonna-s-butter-bean-potato-salad.jpg",
    "thumb": "images/thumbs/dishes/nonna-s-butter-bean-potato-salad.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "3 potatoes per 1 tin butter beans",
      "crushed garlic tsp",
      "chopped parsley",
      "chopped spring onion",
      "Seasoning: black pepper, salt & vinegar & oil (not olive oil)"
    ],
    "method": [
      "Boil some potatoes ± 3 for 1 tin butter beans till soft but not soggy. Peel & slice in rounds.",
      "Drain butter beans.",
      "Take crushed garlic, chopped parsley & sliced spring onion.",
      "Layer your potatoes, beans & chopped parsley, spring onion & garlic.",
      "Season black pepper, salt & vinegar & oil."
    ],
    "notes": [
      "Delicious."
    ]
  },
  "nonna-s-artichoke-chicken": {
    "title": "Nonna's Artichoke & Chicken",
    "from": "Nonna",
    "date": null,
    "serves": null,
    "category": "Meat, Chicken & Fish",
    "person": "nonna",
    "pages": [
      "images/pages/p170451.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170451.jpg"
    ],
    "photo": "images/dishes/nonna-s-artichoke-chicken.jpg",
    "thumb": "images/thumbs/dishes/nonna-s-artichoke-chicken.jpg",
    "photoReal": true,
    "uses": [],
    "ingredients": [
      "1 chicken cut into pieces",
      "Approx 4 - 5 artichokes",
      "1 tin peas, drained",
      "Approx 4 - 5 potatoes peeled & sliced in half twice lengthwise"
    ],
    "method": [
      "Parboil chicken pieces.",
      "Parboild artichokes then remove outer hard leaves of artichokes, cut artichokes lengthwise.",
      "Parboil peeled potatoes.",
      "Make a mixture of:",
      "Flour, breadcrumbs, salt, pepper, crushed garlic, salt, origanum & chopped parsley.",
      "In a frying pan heat some oil & butter with a cube of chicken stock melted into the oil. [NOT DISSOLVED]",
      "Dip dried chicken pieces into mixture & fry gently till golden, remove & put pieces in a big casserole dish at one end.",
      "Do the same with the potatoes using the same frying pan as the chicken, remove & put potato pieces next to the chicken.",
      "Repeat procedure [dip into mixture & then fry gently] with the artichokes, remove & put next to the potatoes.",
      "Lastly, take drained peas and do the same as the above, remove & put next to the artichokes."
    ],
    "notes": [
      "It looks wonderful in the dish - different colours & textures - with bits of crumbs from the mixture. Serve hot with a delicious salad and some warm bread/rolls."
    ]
  },
  "cape-bobotie": {
    "title": "Cape Bobotie",
    "from": "Sheila",
    "date": null,
    "serves": "6-8",
    "category": "Meat, Chicken & Fish",
    "person": "sheila",
    "pages": [
      "images/pages/p170458.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170458.jpg"
    ],
    "photo": "images/dishes/cape-bobotie.jpg",
    "thumb": "images/thumbs/dishes/cape-bobotie.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "2 onions, sliced into rings",
      "Sunflower oil for frying",
      "1 kg beef mince [can use soya mince for vegetarians]",
      "1 slice white bread",
      "250ml [1 cup] milk",
      "15 ml [1 tablespoon] curry powder",
      "15 ml [1 tablespoon] sugar",
      "10 ml [2 teaspoon] salt",
      "2 ml [1/2 teaspoon] milled pepper",
      "5 ml [1 teaspoon] turmeric",
      "25 ml [5 teaspoon] vinegar",
      "125ml [1/2 cup] seedless raisins",
      "45 ml [3 tablespoons] mild chutney",
      "2 eggs",
      "4 bay leaves"
    ],
    "method": [
      "Saute onions in a little oil until golden.",
      "Add beef mince & saute until browned.",
      "Soak bread in milk - squeeze out milk & keep aside.",
      "Crumble bread & add to mince mixture.",
      "Mix in remaining ingredients except eggs, leftover milk & bay leaves.",
      "Place mixture in a greased ovenproof dish.",
      "Roll up bay leaves & press upright into mince mixture.",
      "Whisk milk & egg together & pour gently over mince mixture.",
      "Bake at 180 for approx 45 minutes or until topping set & golden."
    ],
    "notes": []
  },
  "brisket-in-coke": {
    "title": "Brisket in Coke",
    "from": "Granny Naomi",
    "date": null,
    "serves": null,
    "category": "Meat, Chicken & Fish",
    "person": "granny-naomi",
    "pages": [
      "images/pages/p170505.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170505.jpg"
    ],
    "photo": "images/dishes/brisket-in-coke.jpg",
    "thumb": "images/thumbs/dishes/brisket-in-coke.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "2 ½ kg fresh brisket off the bone (flat)",
      "Mix together:",
      "250 ml tomato sauce",
      "125 ml chutney",
      "250 ml Coca Cola (not diet)",
      "500 ml water"
    ],
    "method": [
      "Rub brisket with 1 spoon brown sugar and 1 pkt onion soup mix.",
      "Pour over the above mixture and bake 170c for 3 hours covered, and then 1 hour uncovered.",
      "Baste frequently."
    ],
    "notes": []
  },
  "pulpetti": {
    "title": "Pulpetti",
    "from": "Nonna",
    "date": null,
    "serves": null,
    "category": "Meat, Chicken & Fish",
    "person": "nonna",
    "pages": [
      "images/pages/p170513.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170513.jpg"
    ],
    "photo": "images/dishes/pulpetti.jpg",
    "thumb": "images/thumbs/dishes/pulpetti.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "3 cups mince (or veggie mince)",
      "1 cup bread & milk",
      "4 eggs",
      "Chopped parsley, origanum, mint, spices",
      "Salt & pepper",
      "1 teaspoon baking powder",
      "1 cup grated Pecorino",
      "1 grated onion",
      "3 chop garlic",
      "1 drop gin (± teaspoon)"
    ],
    "method": [
      "Mix together.",
      "Roll into smallish balls.",
      "Roll in flour.",
      "Fry slowly in oil & butter."
    ],
    "notes": []
  },
  "minestroni-soup": {
    "title": "Minestrone Soup",
    "from": "Sheila",
    "date": null,
    "serves": "6-8",
    "category": "Soups & Starters",
    "person": "sheila",
    "pages": [
      "images/pages/p170520.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170520.jpg"
    ],
    "photo": "images/dishes/minestroni-soup.jpg",
    "thumb": "images/thumbs/dishes/minestroni-soup.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "Oil & butter",
      "2 onions chopped",
      "3 carrots chopped",
      "3 celery chopped [or celery salt]",
      "250g potato chopped",
      "2-3 baby marrow chopped",
      "85 g green beans chopped",
      "250g cabbage chopped",
      "2 x 400g tinned tomato mashed and undrained [keep the juice]",
      "1 tin butter beans with liquid",
      "1 tin peas with the liquid",
      "8 - 10 cups water",
      "3 beef/vegetable stock",
      "Any kind of pasta"
    ],
    "method": [
      "Fry onion in a large pot in butter & oil until golden.",
      "Add all the fresh vegetables [celery salt] & fry.",
      "Stir in the 8-10 cups water.",
      "Add crushed stock - stir.",
      "Add mashed tomato + juice, salt & pepper - stir.",
      "Bring to the boil - reduce heat.",
      "Add tins of butter beans & peas (include juices) - stir - bring to the boil slightly.",
      "Reduce heat, cover - stir and let simmer slowly for approx 1 hour - stirring often.",
      "DON'T LET VEGGIES STICK TO THE BOTTOM OR BURN!",
      "About 1/2 hour before serving add approx a handful of pasta to the soup & let cook."
    ],
    "notes": [
      "Serve with grated pecorino cheese."
    ]
  },
  "easy-no-meat-lasagne-quite-a-big-dish": {
    "title": "Easy 'No Meat' Lasagne",
    "from": "Sheila",
    "date": null,
    "serves": null,
    "category": "Pasta & Rice",
    "person": "sheila",
    "pages": [
      "images/pages/p170556.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170556.jpg"
    ],
    "photo": "images/dishes/easy-no-meat-lasagne-quite-a-big-dish.jpg",
    "thumb": "images/thumbs/dishes/easy-no-meat-lasagne-quite-a-big-dish.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "Defrost Seberini's Neapolitan Sauce & Aletta's Pesto Sauce",
      "Box 500gm Lasagne (big) pre-cooked",
      "Grated cheese (Pecorino) + some grated Mozzarella",
      "White Sauce:",
      "4 tablespoon butter",
      "4 tablespoon flour",
      "4 cups milk",
      "Salt, pepper"
    ],
    "method": [
      "Method White Sauce",
      "Melt the butter & remove saucepan from stove.",
      "Add the flour & mix with butter thoroughly.",
      "Still off stove, add milk, mix into mixture & return to stove.",
      "Add salt & pepper.",
      "Turn down heat & keep stirring until sauce thickens.",
      "Don't let it get too thick.",
      "Lasagna Method",
      "Take lasagna Pyrex dish & line bottom with pre-cooked lasagna.",
      "Cover lasagne with tomato sauce & on top of that Aletta's Pesto sauce.",
      "Cover with white sauce.",
      "Cover with pecorino and mozzarella.",
      "Repeat the layers until you finish with white sauce & cheese.",
      "Preheat oven to 180°C & bake in oven till browned & bubbling ± 1/2 to 3/4 hr.",
      "Test if ready with long narrow knife pressed into centre of lasagne. If knife comes out hot, it's ready to serve!"
    ],
    "notes": [
      "To make a smaller lasagne, use 250gms lasagne & 1/2 the quantities for the white sauce.",
      "Enjoy, it's lovely!"
    ]
  },
  "gnocchi": {
    "title": "Gnocchi",
    "from": "Sheila",
    "date": null,
    "serves": null,
    "category": "Pasta & Rice",
    "person": "sheila",
    "pages": [
      "images/pages/p170604.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p170604.jpg"
    ],
    "photo": "images/dishes/gnocchi.jpg",
    "thumb": "images/thumbs/dishes/gnocchi.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "Store bought Gnocchi",
      "± 1/4 lb butter",
      "± 3/4 cup grated pecorino cheese",
      "Neapolitan tomato sauce"
    ],
    "method": [
      "Tomato sauce - use Seberini's Neapolitan sauce.",
      "Method",
      "Throw slices of gnocchi into salted boiling water. They rise to the top, remove with strainer, drain & place in serving dish.",
      "Heat butter till brown.",
      "a. Sprinkle cheese over gnocchi.",
      "b. Then pour hot butter over gnocchi.",
      "c. Lastly pour over hot, home-made fresh tomato sauce.",
      "Serve immediately!"
    ],
    "notes": [
      "Gnocchi (or you can buy frozen, just as good!)",
      "Absolutely delicious"
    ]
  },
  "chicken-ala-familia": {
    "title": "Chicken à la Familia",
    "from": "The Goldberg girls",
    "date": null,
    "serves": null,
    "category": "Meat, Chicken & Fish",
    "person": "goldberg-girls",
    "pages": [
      "images/pages/p-chicken-ala-familia.jpg"
    ],
    "pageThumbs": [
      "images/thumbs/pages/p-chicken-ala-familia.jpg"
    ],
    "photo": "images/dishes/chicken-ala-familia.jpg",
    "thumb": "images/thumbs/dishes/chicken-ala-familia.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "Chicken pieces",
      "Oil",
      "Tomato sauce",
      "Wine (red or white)",
      "Salt, pepper, origanum, mixed spices",
      "Any veggies:",
      "Baby marrow sliced lengthwise",
      "Sliced onion",
      "Garlic in skin",
      "Potato quartered",
      "Carrots",
      "Green pepper",
      "Mushroom",
      "Sliced brinjals",
      "Or what you want"
    ],
    "method": [
      "Place chicken pieces in roasting pan.",
      "Surround with onion, garlic & all veggies.",
      "Pour over wine, oil then tomato sauce (from bottle).",
      "Season.",
      "Preheat 180°.",
      "Cook, basting, turning, till nice & sticky."
    ],
    "notes": [
      "Serve with rice & salad."
    ]
  },
  "roz-s-minute-cake": {
    "title": "Roz's Minute Cake",
    "from": "Roz",
    "date": null,
    "serves": null,
    "category": "Baking",
    "person": "roz",
    "pages": [],
    "pageThumbs": [],
    "photo": "images/dishes/roz-s-minute-cake.jpg",
    "thumb": "images/thumbs/dishes/roz-s-minute-cake.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "1½ cups flour",
      "¾ cup sugar",
      "2 teaspoons baking powder",
      "¼ teaspoon salt",
      "½ cup milk",
      "2 eggs",
      "Vanilla",
      "125g butter"
    ],
    "method": [
      "Sift dry ingredients into a large bowl.",
      "Make a well in the centre. Add milk, vanilla & eggs.",
      "Lastly add butter, which must be very soft but not lumpy. Mix well.",
      "Bake in a holey (ring) cake tin at 175°C for 45-50 minutes."
    ],
    "notes": [
      "Apple Minute Cake: cut 1 large apple into 16 segments & push into the batter all round the edge of the cake. Cover the cake with cinnamon & sugar.",
      "Marble Minute Cake: remove ⅓ of the batter & blend with 1 tablespoon cocoa mixed with a little extra milk & sugar. Pour the white batter into the tin, then drop spoonfuls of cocoa batter over it & streak it slightly."
    ]
  },
  "roz-s-butternut-roast-vegetables": {
    "title": "Roz's Butternut & Roast Vegetables",
    "from": "Roz",
    "date": null,
    "serves": null,
    "category": "Vegetables & Sides",
    "person": "roz",
    "pages": [],
    "pageThumbs": [],
    "photo": "images/dishes/roz-s-butternut-roast-vegetables.jpg",
    "thumb": "images/thumbs/dishes/roz-s-butternut-roast-vegetables.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "Butternut:",
      "Whole butternuts",
      "Brown sugar",
      "Cinnamon",
      "Baked vegetables:",
      "Butternut, pumpkin, sweet potatoes, carrots & baby potatoes",
      "Garlic (optional)",
      "Olive oil & coconut oil",
      "Spices for vegetables (from Woolies etc)",
      "Mielie chunks"
    ],
    "method": [
      "Butternut:",
      "Bake whole butternuts till soft.",
      "Split in half & remove and discard the seeds.",
      "Sprinkle over brown sugar & cinnamon & bake till brown & delicious.",
      "Baked vegetables:",
      "Cut the raw vegetables into chunks.",
      "Pour over olive oil & coconut oil & the vegetable spices, then bake.",
      "Before serving, bake mielie chunks in vegetable spices & oil & add to the other baked vegetables."
    ],
    "notes": [
      "We buy and use a multitude of herbs and spices and add them to create taste changes.",
      "Only use extra virgin olive oil for salad, never for cooking. For cooking: ordinary olive oil, canola & coconut oil."
    ]
  },
  "lorraine-s-cheese-cake": {
    "title": "Lorraine's Cheese Cake",
    "from": "Lorraine",
    "date": null,
    "serves": null,
    "category": "Desserts",
    "person": "lorraine",
    "pages": [],
    "pageThumbs": [],
    "photo": "images/dishes/lorraine-s-cheese-cake.jpg",
    "thumb": "images/thumbs/dishes/lorraine-s-cheese-cake.jpg",
    "photoReal": false,
    "uses": [],
    "ingredients": [
      "Crust:",
      "1 packet Marie biscuits",
      "Melted butter",
      "Filling:",
      "750g cream cheese",
      "250ml cream",
      "3 eggs & 1 extra egg white",
      "¾ cup sugar",
      "1 full dessertspoon flour",
      "1 level dessertspoon custard powder",
      "1 tablespoon brandy",
      "1 tablespoon lemon juice"
    ],
    "method": [
      "Crust:",
      "Crush the Marie biscuits in a food processor. Add enough melted butter to make them sticky.",
      "Line a springform pan with this.",
      "Filling:",
      "Separate the eggs.",
      "Mix all the ingredients together by hand till smooth, except the egg whites.",
      "Beat the whites till stiff & lastly fold into the mixture.",
      "Pour into the crust & bake at 180°C for 20-25 minutes (do not open the oven!).",
      "Then switch off the oven & leave for another 40-45 minutes in the oven. Remember not to open the oven until the 40-45 minutes are up.",
      "Warm up before serving, then remove the springform, place on a platter & enjoy!"
    ],
    "notes": [
      "This freezes very well. Wrap well in Glad Wrap."
    ]
  }
};

const MOCK = {
  "people": {
    "nonna": {
      "name": "Nonna",
      "relation": "Sheila's mother-in-law",
      "bio": "She was Italian but born in Turkey, raised on the Island Rhodes, married an Italian Slav & called herself 'oriental' Italian. She was just the most wonderful cook. She brought Italian cooking into the Seberini family and many more family members. Her Italian recipes are unmatched.",
      "photo": "images/people/nonna.jpg"
    },
    "aletta": {
      "name": "Aletta Taranto",
      "relation": "Sheila's friend from their Swaziland days",
      "bio": "Also married to an Italian, she helped Sheila begin her 'like' of cooking. (From Sheila's introduction)",
      "photo": "images/people/aletta.jpg"
    },
    "sheila": {
      "name": "Sheila",
      "relation": "Sheila Seberini",
      "bio": null,
      "photo": "images/people/sheila.jpg"
    },
    "granny-naomi": {
      "name": "Granny Naomi",
      "relation": "Sheila's late mother",
      "bio": "Her parents came from Riga & she had wonderful recipes to share as well as her 'own' wonderful food. The ultra host who could with ease handle a 20 person Shabbat dinner followed by an eqally impressive Sunday lunch. She fed us all and was the matriarch of the family. Definitely set the standard for family meals.",
      "photo": "images/people/granny-naomi.jpg"
    },
    "simy": {
      "name": "Simy",
      "relation": "Sheila's late daughter in law",
      "bio": "Simy will always be remembered for her lovely smile and friendly nature. Her Fish cakes and Mac and cheese were famous.",
      "photo": "images/people/simy.jpg"
    },
    "goldberg-girls": {
      "name": "The Goldberg girls",
      "relation": "Sheila, Rosy, Lorraine and Naomi.",
      "bio": "The females of the Goldberg clan, all excellent cooks in their own right. Lorraine famous for her cheese-cake and Rosy for her butternut roast vegetables.",
      "photo": null
    },
    "roz": {
      "name": "Roz",
      "relation": "Sheila's sister",
      "bio": "Roz has hosted many wonderful Friday nights at her colourful home in Waverly. She makes many wonderful dishes and the Roast vegetables with butternut really stands out.",
      "photo": "images/people/roz.jpg"
    },
    "lorraine": {
      "name": "Lorraine",
      "relation": "Sheila's sister",
      "bio": "Lorraine hosted many Friday night dinners at her lovely home in Waverly and now Melrose. She made many delicious dishes but the most famous and internationally renowned is her cheese-cake.",
      "photo": "images/people/lorraine.jpg"
    }
  },
  "categories": [
    {
      "name": "Soups & Starters",
      "ids": [
        "caponata",
        "minestroni-soup",
        "nonna-s-butter-bean-potato-salad"
      ]
    },
    {
      "name": "Meat, Chicken & Fish",
      "ids": [
        "brisket-in-coke",
        "cape-bobotie",
        "chicken-ala-familia",
        "fish-cakes",
        "nonna-s-artichoke-chicken",
        "pulpetti"
      ]
    },
    {
      "name": "Pasta & Rice",
      "ids": [
        "easy-no-meat-lasagne-quite-a-big-dish",
        "gnocchi"
      ]
    },
    {
      "name": "Vegetables & Sides",
      "ids": [
        "roz-s-butternut-roast-vegetables"
      ]
    },
    {
      "name": "Baking",
      "ids": [
        "roz-s-minute-cake"
      ]
    },
    {
      "name": "Desserts",
      "ids": [
        "lorraine-s-cheese-cake"
      ]
    }
  ],
  "intro": [
    "When I first got married 60 years ago to my 'Italian' hubby we settled in Swaziland for 7 years. I had NO clue how to cook but with a little help from my friends, especially my friend Aletta also married to an Italian & I sort of began my 'like' of cooking.",
    "However when we moved back to Jhb I started asking my mother-in-law (who I refer to as 'Nonna - granny') how to make her food.",
    "Now... she was Italian but born in Turkey, raised on the Island Rhodes, married an Italian Slav & called herself 'oriental' Italian. She was just the most wonderful cook & the few recipes I got from her I have kept hidden & only cooked by me for years. By now I had developed a love of cooking & decided to share her few but stunning recipes with you.",
    "Now I decided to pick my mothers brain as well as her parents came from Riga & she had wonderful recipes to share as well as her 'own' wonderful food & thats when I decided to create this book & gather more recipes from family & friends.",
    "Its really been fun & is a 'Pot Pourrie' of all these mixed & scrumptious recipes so kindly given to me.",
    "Thanks all of you for your generosity & willingness to part with your treasures!!"
  ],
  "introPage": "images/pages/p-intro.jpg"
};
