// Builds the site's recipe data (recipes-data.js, next to index.html) from data/recipes.json + data/photos.json.
// Only recipes ticked "Checked" in the editor go live; only photos Sheila approved are shown.
// Usage: node tools/build-site.mjs   → prints the image files the live recipes need (to git add).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import os from "node:os";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const data = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "recipes.json"), "utf8"));
const photos = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "photos.json"), "utf8"));

// Printed personal emails (addresses, family news): never published.
const PRIVATE_PAGES = ["p170357", "p170405"];
// Other names a recipe goes by in other recipes' text, so those mentions link too.
const ALIASES = { "alettas-pesto-sauce": ["Pesto Sauce"], "neopolitan-sauce": ["Neopolitan Sauce", "Neapolitan"] };

const clean = (s) => String(s).replace(/\[\?\]|\[illegible\]/g, "").replace(/\s{2,}/g, " ").replace(/\s+([,.!])/g, "$1").trim();
const lines = (a) => (a || []).map(clean).filter(Boolean);
const exists = (rel) => fs.existsSync(path.join(ROOT, rel));

const live = data.recipes.filter((r) => r.checked);
const liveIds = new Set(live.map((r) => r.id));
const files = new Set(["images/sheila.jpg", `images/pages/${data.intro.page}.jpg`]);
// Small copies for where photos show small (made by tools/make-thumbs.ps1); the full photo is kept for big views.
const thumbJobs = [];
const thumb = (src, w) => {
  const dest = src.replace(/^images\//, "images/thumbs/");
  thumbJobs.push({ src, dest, w });
  files.add(dest);
  return dest;
};
thumb("images/sheila.jpg", 900);
const recipes = {};
const problems = [];

for (const r of live) {
  const pages = (r.pages || []).filter((p) => !PRIVATE_PAGES.includes(p) && exists(`images/pages/${p}.jpg`));
  pages.forEach((p) => files.add(`images/pages/${p}.jpg`));
  if (pages.length < (r.pages || []).length) problems.push(`${r.id}: some pages left out (private or missing)`);

  const ph = photos[r.id];
  const photoFile = `images/dishes/${r.id}.jpg`;
  const hasPhoto = ph?.status === "approved" && exists(photoFile);
  if (hasPhoto) files.add(photoFile);

  const serves = clean(r.serves || "");
  recipes[r.id] = {
    title: clean(r.title), from: clean(r.from || "") || null, date: clean(r.date || "") || null, serves: serves || null,
    category: r.category,
    person: r.personId || null,
    pages: pages.map((p) => `images/pages/${p}.jpg`),
    pageThumbs: pages.map((p) => thumb(`images/pages/${p}.jpg`, 240)),
    photo: hasPhoto ? photoFile : null,
    thumb: hasPhoto ? thumb(photoFile, 200) : null,
    photoReal: hasPhoto && ph.source === "real",
    uses: (r.uses || []).filter((id) => liveIds.has(id)),
    ...(ALIASES[r.id] ? { aliases: ALIASES[r.id] } : {}),
    ingredients: lines(r.ingredients),
    // The site numbers the steps itself, so her own "1." / "2)" at the start of a step would double up.
    method: lines(r.method).map((m) => m.replace(/^\d+\s*[.)]\s+/, "")),
    // "Serves 6-8" is already shown at the top.
    notes: lines(r.notes).filter((n) => !serves || n.replace(/\.$/, "").toLowerCase() !== `serves ${serves}`.toLowerCase()),
  };
}

// Only the people behind live recipes are published (with their photo, if they have one).
const people = {};
for (const p of data.people || []) {
  if (!Object.values(recipes).some((r) => r.person === p.id)) continue;
  const photo = p.photo && exists(p.photo) ? p.photo : null;
  if (photo) files.add(photo);
  people[p.id] = { name: clean(p.name), relation: clean(p.relation || "") || null, bio: clean(p.bio || "") || null, photo };
}
for (const r of Object.values(recipes)) if (r.person && !people[r.person]) r.person = null;

const byTitle = (a, b) => recipes[a].title.localeCompare(recipes[b].title);
const MOCK = {
  people,
  categories: data.categories
    .map((name) => ({ name, ids: Object.keys(recipes).filter((id) => recipes[id].category === name).sort(byTitle) }))
    .filter((c) => c.ids.length),
  intro: data.intro.paragraphs,
  introPage: `images/pages/${data.intro.page}.jpg`,
};

const jobsFile = path.join(os.tmpdir(), "sheilas-thumb-jobs.json");
fs.writeFileSync(jobsFile, JSON.stringify(thumbJobs));
process.stdout.write(execFileSync("powershell", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", path.join(ROOT, "tools", "make-thumbs.ps1"), "-Jobs", jobsFile], { encoding: "utf8" }));

const out = `// Generated by tools/build-site.mjs from data/recipes.json - don't edit by hand.
// ${live.length} checked recipes.
const RECIPES = ${JSON.stringify(recipes, null, 2)};

const MOCK = ${JSON.stringify(MOCK, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "recipes-data.js"), out);

console.log(`${live.length} live recipes (${Object.values(recipes).filter((r) => r.photo).length} with a photo)`);
for (const c of MOCK.categories) console.log(`  ${c.name}: ${c.ids.map((id) => recipes[id].title).join(", ")}`);
for (const p of problems) console.log("NOTE", p);
console.log("FILES " + [...files].join(" "));
