// Builds the site's recipe data (mockups/recipes-data.js) from data/recipes.json + data/photos.json.
// Only recipes ticked "Checked" in the editor go live; only photos Sheila approved are shown.
// Usage: node tools/build-site.mjs   → prints the image files the live recipes need (to git add).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const data = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "recipes.json"), "utf8"));
const photos = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "photos.json"), "utf8"));

// Printed personal emails (addresses, family news): never published.
const PRIVATE_PAGES = ["p170357", "p170405"];
// Other names a recipe goes by in other recipes' text, so those mentions link too.
const ALIASES = { "alettas-pesto-sauce": ["Pesto Sauce"], "neopolitan-sauce": ["Neopolitan Sauce", "Neapolitan"] };

const clean = (s) => String(s).replace(/\[\?\]|\[illegible\]/g, "").replace(/\s{2,}/g, " ").replace(/\s+([,.!])/g, "$1").trim();
const lines = (a) => (a || []).map(clean).filter(Boolean);
const exists = (rel) => fs.existsSync(path.join(ROOT, rel));

const live = data.recipes.filter((r) => r.checked);
const liveIds = new Set(live.map((r) => r.id));
const files = new Set(["images/sheila.jpg", `images/pages/${data.intro.page}.jpg`]);
const recipes = {};
const problems = [];

for (const r of live) {
  const pages = (r.pages || []).filter((p) => !PRIVATE_PAGES.includes(p) && exists(`images/pages/${p}.jpg`));
  pages.forEach((p) => files.add(`images/pages/${p}.jpg`));
  if (pages.length < (r.pages || []).length) problems.push(`${r.id}: some pages left out (private or missing)`);

  const ph = photos[r.id];
  const photoFile = `images/dishes/${r.id}.jpg`;
  const hasPhoto = ph?.status === "approved" && exists(photoFile);
  if (hasPhoto) files.add(photoFile);

  const serves = clean(r.serves || "");
  recipes[r.id] = {
    title: clean(r.title), from: clean(r.from || "") || null, date: clean(r.date || "") || null, serves: serves || null,
    category: r.category,
    pages: pages.map((p) => `../images/pages/${p}.jpg`),
    photo: hasPhoto ? `../${photoFile}` : null,
    photoReal: hasPhoto && ph.source === "real",
    uses: (r.uses || []).filter((id) => liveIds.has(id)),
    ...(ALIASES[r.id] ? { aliases: ALIASES[r.id] } : {}),
    ingredients: lines(r.ingredients),
    method: lines(r.method),
    // "Serves 6-8" is already shown at the top.
    notes: lines(r.notes).filter((n) => !serves || n.replace(/\.$/, "").toLowerCase() !== `serves ${serves}`.toLowerCase()),
  };
}

const byTitle = (a, b) => recipes[a].title.localeCompare(recipes[b].title);
const MOCK = {
  categories: data.categories
    .map((name) => ({ name, ids: Object.keys(recipes).filter((id) => recipes[id].category === name).sort(byTitle) }))
    .filter((c) => c.ids.length),
  intro: data.intro.paragraphs,
  introPage: `../images/pages/${data.intro.page}.jpg`,
};

const out = `// Generated by tools/build-site.mjs from data/recipes.json - don't edit by hand.
// ${live.length} checked recipes.
const RECIPES = ${JSON.stringify(recipes, null, 2)};

const MOCK = ${JSON.stringify(MOCK, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "mockups", "recipes-data.js"), out);

console.log(`${live.length} live recipes (${Object.values(recipes).filter((r) => r.photo).length} with a photo)`);
for (const c of MOCK.categories) console.log(`  ${c.name}: ${c.ids.map((id) => recipes[id].title).join(", ")}`);
for (const p of problems) console.log("NOTE", p);
console.log("FILES " + [...files].join(" "));
